### ISSUE TITLE
Unnecessary volume

### ISSUE THREAD

**Issue by michaelgerakis** [kyleholzinger/c.r.a.p.#1]
Why not add dist/ to gitignore? Especially if there's a build rule, its a waste of space to include them.

**Comment by michaelgerakis** [comment]
bump

**Comment by kyleholzinger** [comment]
No

**Comment by kyleholzinger** [comment]
Meant yes* fixed with [c27e303](https://github.com/kyleholzinger/c.r.a.p./commit/c27e3035a2efb0f8a491abb5badb764dbffbe738)
